services:
  flyway:
    image: flyway/flyway:latest
    volumes:
      - ./flyway/conf:/flyway/conf
      - ./flyway/sql:/flyway/sql
    command: [ "migrate", "-target=${FLYWAY_TARGET}" ]
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data

  app:
    depends_on:
      - db
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env

volumes:
  db:
