package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"fmt"
	"time"

	"github.com/M1RCLE/comments/graph/generated"
	"github.com/M1RCLE/comments/src/entity"
)

// CreationTime is the resolver for the creationTime field.
func (r *commentResolver) CreationTime(ctx context.Context, obj *entity.Comment) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: CreationTime - creationTime"))
}

// Comment returns generated.CommentResolver implementation.
func (r *Resolver) Comment() generated.CommentResolver { return &commentResolver{r} }

type commentResolver struct{ *Resolver }
